2024-09-23 11:21:45,146 WARNING Bad Request: /register/ 241 
2024-09-23 11:21:46,021 WARNING Bad Request: /login/ 241 
2024-09-23 11:21:47,308 WARNING Bad Request: /login/ 241 
2024-09-23 11:21:47,753 WARNING Unauthorized: /logout/ 241 
2024-09-23 11:21:48,665 ERROR Internal Server Error: /logout/ 241 
Traceback (most recent call last):
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/backend/users/auth_views.py", line 110, in post
    old_refresh = RefreshToken(token)
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework_simplejwt/tokens.py", line 61, in __init__
    self.verify()
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework_simplejwt/tokens.py", line 245, in verify
    self.check_blacklist()
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework_simplejwt/tokens.py", line 257, in check_blacklist
    raise TokenError(_("Token is blacklisted"))
rest_framework_simplejwt.exceptions.TokenError: Token is blacklisted
2024-09-23 11:21:49,527 WARNING Unauthorized: /reviews/ 241 
2024-09-23 11:21:50,393 WARNING Bad Request: /reviews/ 241 
2024-09-23 11:21:50,420 WARNING Forbidden: /reviews/ 241 
2024-09-23 11:21:52,938 WARNING Bad Request: /reviews/1/ 241 
2024-09-23 11:21:52,959 WARNING Bad Request: /reviews/1/ 241 
2024-09-23 11:21:52,976 WARNING Unauthorized: /reviews/1/ 241 
2024-09-23 11:21:54,336 WARNING Unauthorized: /reviews/1/ 241 
2024-09-23 11:21:54,866 WARNING Forbidden: /reviews/2/ 241 
2024-09-23 11:22:52,274 INFO Watching for file changes with StatReloader 668 
2024-09-23 11:25:37,131 WARNING Bad Request: /register/ 241 
2024-09-23 11:25:38,116 WARNING Bad Request: /login/ 241 
2024-09-23 11:25:39,509 WARNING Bad Request: /login/ 241 
2024-09-23 11:25:39,982 WARNING Unauthorized: /logout/ 241 
2024-09-23 11:25:40,938 ERROR Internal Server Error: /logout/ 241 
Traceback (most recent call last):
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/backend/users/auth_views.py", line 110, in post
    old_refresh = RefreshToken(token)
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework_simplejwt/tokens.py", line 61, in __init__
    self.verify()
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework_simplejwt/tokens.py", line 245, in verify
    self.check_blacklist()
  File "/home/mrchatzopoulos/PycharmProjects/virtualmarketplace/.venv/lib/python3.12/site-packages/rest_framework_simplejwt/tokens.py", line 257, in check_blacklist
    raise TokenError(_("Token is blacklisted"))
rest_framework_simplejwt.exceptions.TokenError: Token is blacklisted
2024-09-23 11:25:41,892 WARNING Unauthorized: /reviews/ 241 
2024-09-23 11:25:42,823 WARNING Bad Request: /reviews/ 241 
2024-09-23 11:25:42,851 WARNING Forbidden: /reviews/ 241 
2024-09-23 11:25:45,745 WARNING Bad Request: /reviews/1/ 241 
2024-09-23 11:25:45,782 WARNING Bad Request: /reviews/1/ 241 
2024-09-23 11:25:45,810 WARNING Unauthorized: /reviews/1/ 241 
2024-09-23 11:25:48,170 WARNING Unauthorized: /reviews/1/ 241 
2024-09-23 11:25:49,098 WARNING Forbidden: /reviews/2/ 241 
2024-09-23 11:36:36,293 WARNING Bad Request: /cart-item/ 241 
